webmain/games/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.contrib import admin
from games import views

app_name = 'games'
urlpatterns = [
        path('new/', views.addGame, name='addGame'),
    	path('view-all/', views.viewAll, name='viewAll'),
        path('view/<int:game_id>', views.viewGame, name='viewGame'),
    	path('view/<str:game_id>.js', views.staticFile, name='staticFile')
]

webmain/gcp/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.contrib import admin
from gcp import views

app_name = 'gcp'
urlpatterns = [
        path('test/cloudfunction', views.test_cloudfunction, name='test_cloudfunction'),
        path('test/cloudfunction/run', views.test_cloudfunction_run, name='test_cloudfunction_run'),
        path('match/start', views.start_match, name='start_match'),
]

webmain/users/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.contrib import admin
from . import views
from .views import Register

app_name = 'users'
urlpatterns = [
        path('login/', views.my_login, name='login'),
    path('register/', Register.as_view(), name='register'),
    path('logout/', views.my_logout, name ='logout'),    
]

webmain/webmain/urls.py
from django.contrib import admin
from django.urls import path, include
from webmain import views
urlpatterns = [
    path('boards/', include('leaderboards.urls')),    
    path('users/', include('users.urls')),    
    path('games/', include('games.urls')),
    path('gcp/', include('gcp.urls')),
    path('bots/', include('bots.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
]

webmain/templates/base.html
<!doctype html>
<html lang="en">
  {% load staticfiles %}
  <head>
    <link rel="shortcut icon" href="{% static 'favicon/favicon.png' %}"/>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    <!-- Google Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
	  rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'index' %}">ML Arena</a>
      <ul class="navbar-nav mr-auto">
	{% if request.user.is_authenticated %}
	<li class="nav-item dropdown mr-2">
	  <a class="nav-link dropdown-toggle mr" href="#" id="profilesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	    Games
	  </a>
	  <div class="dropdown-menu" aria-labelledby="profilesDropdown">
	    <a class="dropdown-item" href="{% url 'games:addGame'%}">Create New Game</a>

	    <a class="dropdown-item" href="{% url 'games:viewAll' %}">View All Games</a>

	  </div>
	</li>
	<li class="nav-item dropdown mr-2">
	  <a class="nav-link dropdown-toggle" href="#" id="groupsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	    Something Else
	  </a>
	  <div class="dropdown-menu" aria-labelledby="groupsDropdown">
	    <a class="dropdown-item" href="#">Find Study Groups</a>
	    <a class="dropdown-item" href="#">My Study Groups</a>
	  </div>
	</li>


	<li class="nav-item">
	  <a class="nav-link" href="#">Messages</a>
	</li>
	{% endif %}
      </ul>
      <ul class="nav nav-tabs">
	<li class = "nav-item dropdown">
	  {% if request.user.is_authenticated %}
	  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Hello, {{request.user.username}}</a>
	  <div class="dropdown-menu dropdown-menu-right">
	    <a class="dropdown-item" href="{% url 'users:logout'%}">Logout</a>
	    <a class="dropdown-item" href="#">Settings</a>	      
	  </div>

	  


	  {% else %}
	  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Login/Register </a>
	  <div class="dropdown-menu dropdown-menu-right">
	    <a class="dropdown-item" href="{% url 'users:login' %}">Login </a>
	    <a class="dropdown-item" href="{% url 'users:register' %}">Register</a>
	  </div>
	  {% endif %}

	</li>
	
      </ul>
    </nav>

    {% if messages  %}
    <div class="row justify-content-md-center my">
      {% if messages %}
      {% for message in messages %}
      <div style="position:fixed; z-index: 99999;" class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %} my-2">  <!-- singular -->
	<a class="close" data-dismiss="alert">×</a>
	{{ message|safe }}
      </div>
      {% endfor %}
      {% endif %}
    </div>
    {% endif %}

    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
  </body>
</html>