webmain/bots/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.contrib import admin
from bots import views

app_name = 'bots'
urlpatterns = [
        path('new/<int:game_id>/', views.addBot, name='addBot'),
        path('view/<int:bot_id>/', views.viewBot, name='viewBot'),
    	path('viewMatch/<int:match_id>/', views.viewMatch, name='viewMatch')
]

webmain/games/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.contrib import admin
from games import views

app_name = 'games'
urlpatterns = [
        path('new/', views.addGame, name='addGame'),
    	path('view-all/', views.viewAll, name='viewAll'),
        path('view/<int:game_id>', views.viewGame, name='viewGame'),
    	path('view/<str:game_id>.js', views.staticFile, name='staticFile')
]

webmain/gcp/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.contrib import admin
from gcp import views

app_name = 'gcp'
urlpatterns = [
        path('test/cloudfunction', views.test_cloudfunction, name='test_cloudfunction'),
        path('test/cloudfunction/run', views.test_cloudfunction_run, name='test_cloudfunction_run'),
        path('match/start', views.start_match, name='start_match'),
]

webmain/leaderboards/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'board'
urlpatterns = [
        path('view/<int:game_id>/', views.view, name='viewBoard'),
    path('matchup/<int:game_id>/', views.get_match, name='matchup'),    
        path('update/<int:match_pk>/<int:winner>/', views.update_board, name='matchUpdate'),    
]

webmain/webmain/urls.py
from django.contrib import admin
from django.urls import path, include
from webmain import views
urlpatterns = [
    path('boards/', include('leaderboards.urls')),    
    path('users/', include('users.urls')),    
    path('games/', include('games.urls')),
    path('gcp/', include('gcp.urls')),
    path('bots/', include('bots.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
]

webmain/games/models.py
from django.db import models
from django.utils import timezone

class Game(models.Model):
    name = models.CharField(max_length=50)
    desc = models.TextField(blank=True, null=True)
    renderer_file = models.TextField()
    
    def __str__(self):
        return self.name

class Match(models.Model):
    game = models.ForeignKey(Game, on_delete=models.SET_NULL, null=True)
    bot1 = models.ForeignKey('bots.Bot', on_delete=models.SET_NULL, null=True, related_name='bot1')
    bot2 = models.ForeignKey('bots.Bot', on_delete=models.SET_NULL, null=True, related_name='bot2')
    state = models.IntegerField(default=0)
    timestamp = models.DateTimeField(default=timezone.now)
    
class MatchRecord(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    winner_number = models.IntegerField(default=0)

class GameFrame(models.Model):
    frame_num = models.IntegerField()
    state = models.TextField()
    match_record = models.ForeignKey(MatchRecord, on_delete=models.CASCADE)
    

webmain/games/forms.py
from django import forms
from .models import Game

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['name','desc','renderer_file']

webmain/games/views.py
import io
import os
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import GameForm
from .models import Game
from django.contrib import messages
from django.urls import reverse
from gcp.views import create_cloudfunction
import os
# Create your views here.


def addGame(request):
    # a = "dataeihfjoqiej"
    # return render(request, 'games/viewGroup.html')
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = GameForm(request.POST)
        print(request.FILES)
        # check whether it's valid:
        if form.is_valid():
            new_game = form.save()

            fp = io.BufferedReader(request.FILES['game_file'])
            print(fp)
            create_cloudfunction(fp, "game" + str(new_game.id), "game")

                
            messages.success(request, "You made a new game")
            return HttpResponseRedirect(reverse('games:viewGame', kwargs={'game_id':new_game.id}))
        print (form.errors)
    # if a GET (or any other method) we'll create a blank form
    else:
        form = GameForm()
    return render(request, 'games/viewGroup.html', {'form': form})


def viewAll(request):
    games_list = Game.objects.all()

    return render(request, 'games/viewAll.html', {'games':games_list})

def viewGame(request, game_id=None):
    game = None
    if game_id:
        game = Game.objects.get(pk=game_id)
    return render(request, 'games/viewGame.html', {'game':game})

def staticFile(request, game_id=None):
    module_dir = os.path.dirname(__file__)
    file_path = os.path.join(module_dir, 'files/' + str(game_id) + '.js')
    with open(file_path, 'rb') as fp:
        response = HttpResponse(content=fp)
        response['Content-Type'] = 'text/javascript'
        return response

webmain/games/templates/games/gameCreated.html
You made a game

webmain/games/templates/games/viewAll.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <br/>
  <h1 class="display-3"> Games List </h1>
  <p class="lead" style="margin-left:10px"> List of all the games you've created </p>
  <hr class="my-4">
  {% for game in games %}
  {% if forloop.counter0|divisibleby:"3" %}
  <div class="row mt-4">
  {%endif%}  

    <div class="col-4"> 
      <div class="card" style="width: 100%">
	<div class="card-body">
	  <h5 class="card-title">{{game.name}}</h5>
	  <h6 class="card-subtitle mb-2 text-muted">{{game.file}}</h6>
	  <p class="card-text"> {{game.desc}} </p>
	  <a href="{% url 'board:viewBoard' game.id %}" class="card-link"> Leaderboard </a>
	  <a href="{% url 'games:viewGame' game.id %}" class="card-link"> Game Info </a>
	</div>
      </div>
    </div>

  {% if forloop.counter|divisibleby:"3" or forloop.last%}    
  </div>
  {%endif%}
  {%endfor%}

</div>
{% endblock %}

webmain/games/templates/games/viewGame.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">	
      <h4>Game Title: {{game.name}} </h4>
      <p> {{game.desc}} </p>
      <a class="btn btn-info" href="{% url 'bots:addBot' game.id %}">Upload a bot</a>
    </div>
{% endblock %}

webmain/games/templates/games/viewGroup.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content%}
<div style="margin-left:20px;">
  <br/>
  <h1 class="display-3"> Create New Game </h1>
  <p class="lead" style="margin-left:10px"> Specify a name and description for your game </p>
  <hr class="my-4" style="max-width:95%">
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row mx-0">
	<div class="input-field col" style="max-width:500px">
	  <label for="name">Name</label>
	  {% render_field form.name class+="form-control" %}
	</div>
      </div>
      <br/>
      <div class="row mx-0">
	<div class="input-field col" style="max-width:750px">
	  <label for="name">Description</label>
	  {% render_field form.desc class+="form-control" %}
	</div>
      </div>
      <br/>
      <div class="row mx-0">
	  <div class="input-field col" style="max-width:750px">
	      <label for="name">Rendering Javascrip</label>
	      {% render_field form.renderer_file class+="form-control" %}
	  </div>
      </div>
      <br/>
      <div class="row mx-0">
	<div class="input-field col" style="max-width:750px">
	    <input type="file" name="game_file" class="form-control-file" required="" id="id_game_file">
	</div>
      </div>
      <br/>
      <input class="btn btn-info" type="submit" value="Submit">
    </form>
  </div>
</div>
{%endblock%}